### ISSUE TITLE
Clarifying expected use

### ISSUE THREAD

**Issue by charlietomo** [oznu/homebridge-unifi-occupancy-sensor#1]
Just testing this out and wanted to check as the behaviour wasn't as I expected and I couldn't see anything in the readme.
If I have multiple MAC addresses in the watch list, should I have one occupancy sensor, or an occupancy sensor per MAC address? At the moment I see one sensor, but would have expected multiple. If that is right, can I put multiple accessories in the config.json in order to recognise multiple MAC addresses separately?

**Comment by oznu** [comment]
Depending on your use case, both options will work.

Personally, I have two instances of this running on homebridge. One just has me, the other has everyone who lives in the house. Why? It means I can setup automations that are triggered if at least one person is home, or if just I am home - or not home.

This is how my `config.json` looks:

```
"accessories": [
  {
    "accessory": "UniFi Occupancy Sensor",
    "name": "oznu sensor",
    "unifi": {
      "controller": "https://unifi",
      "username": "api",
      "password": "xxxx"
    },
    "watch": ["44:00:00:00:00:00"],
    "watchGuests": false
  },
  {
    "accessory": "UniFi Occupancy Sensor",
    "name": "everyone sensor",
    "unifi": {
      "controller": "https://unifi",
      "username": "api",
      "password": "xxxx"
    },
    "watch": ["44:00:00:00:00:00", "30:00:00:00:00:00", "22:00:00:00:00:00"],
    "watchGuests": false
  }
]
```

**Comment by oznu** [comment]
I thought I might mention as well, you might have noticed it takes about 5-10 minutes for the UniFi Controller to send the event that a device has disconnected from the network - which is usually a good thing since you don't want to get false alarms for short disconnects. 

This does make testing pain full slow. An easy solution to this problem is to create a guest network and set `watchGuests` to `false` in your `config.json`. You can then switch to the guest network which will immediately trigger the disconnect event for that device. This speeds up the testing process immensely.

**Comment by charlietomo** [comment]
Excellent, I will test that out later. Thanks for the comprehensive reply.
